init:
  - ps: >-
        if ($env:APPVEYOR_REPO_TAG -eq "true")
        {
            Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v."))"
        }
        else
        {
            Update-AppveyorBuild -Version "1.0.0.$env:APPVEYOR_BUILD_VERSION"
        }

os: Visual Studio 2017
platform: Any CPU
configuration: Release

before_build:
  - ps: nuget restore ReverseGeocoder.sln

build:
  project: ReverseGeocoder.sln
  publish_nuget: true
  publish_nuget_symbols: true

test:
  assemblies:
    - '**\*.tests.dll'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

shallow_clone: true

deploy:
  - provider: GitHub
    name: github_release
    auth_token:
      secure: B8gZhfAArOTHNESIhicNlL/BOgz3dBlqV/TGFReQHe5EVIjhtFWbjc3mvRD83DaI
    artifact: /^ReverseGeocoder.*\.nupkg$/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    name: nuget_release
    api_key:
      secure: PmCWZn5JkAAO7/vZk3yFDrCJMEVbRy3wfAydxiieXtwwIlSYd53Z0MZP3M3KSPFk
    artifact: /^ReverseGeocoder.*\.nupkg$/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
